
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EY3dOakF6TkRJeE0xb1hEVE14TURjd05EQXpOREl4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVZYClpTa0o2YloyYzc0NjF6S0tlNFFOTnlralUxWTUreTJxVkFkTXhXR1A3QXBGTEpJRHNBY3pKNjJZcld0R3F1MDgKbmNKSkEyKzZTaUJ1MXhvUGl0d2tpeFBlK0g3Qnlyanc5TG5uUG5neTdkYTE5OFl6MEdZajl2MGQzZjMySTVFcgpBZ1NqVjZCOGtZMS9IeE5waTNtTHhKckFDNlhhUnNNZHkySU53a2w0MWNTVStKTTB0OFdBZEg5cWN0WDFIV3VvCjg5Vi81N0U0ZlpDbmZjYVFMZCt4NDNqUXBmSXUxK3c0UW5RNXZScFcwdlQ0NmEveGk2Z1poUjFWZXhmc2FkeHIKVUdGZkVWOWd4Z2dWMURWQ2tySmlSUU41VGRTTnhlMXVSdm9QSkF5TjBPV2N4OHozMHdVUCs3MTJ1V01QdEZaSQorZWVySTJXWUZvRnAvVklDWDdFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGNDJ2bUIyb3lkZjhURjRjZ21Wd2xrRENqdG1NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBbmU3Rnc4M05uUG9ZdVhtelZxbGZud3loV1ltTnY2MUR6TEZ6S0NEODZGWWtmWUludwpEVmt3dEp2TEhpZ21GZVZsZ3llQkhhMDBtbTJxTHdiSmxyS3JpeG1sZ3p5NFFGaWxGWi9kOHB6RytCK2xqak5kCk5BUUtvNGpQM3pjZzZjbzRtNHR0bHVoTzh5Vm0wZGJXZnE1RW1yLzhaOXFVaWJ6WDU0bmhtQUxPQUlSL2tnMGkKR1Q2TmFGSUt4dmdlNVRiZTV1cS9QZ3FvWS9keEZjQTN4UzRqc2xZelphRDNDWGFoYWQzWmtCS0xoYm84by8wTAozaVZZejdMM2toS2Q1SCtkZzk0WGxqbmxWL25uZGM0N1RoclFqUW1JTXErU1VzK3JEQ2plNE9nMGlXclFON2tUCmhqc1hYbTRFUG54ZHFlK2dxNVRnMTlyKzNzQ1ZDbEFUZWxEUAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://ee368a1d-cf9b-4911-a39b-dbde3587cc3f.eu-west-2.linodelke.net:443
  name: lke30781

users:
- name: lke30781-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImFIbVRMWXQtSXc5T3JrRzl1RTFrajRnTWc4TDhHOXVycUtKdzZDUkRMUWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tdjZyc2MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZWVkY2ViNDItNWM3Yi00ZjQ4LTg2ZGMtNTBjZGNlMGRkMmE1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.g6RJTVAiOW0NaQyrhatd9yO_KLRrFdBzzgvuRnLDh7o9p_Ip-bfzGik51rDNXg_7yPNrbtNhzqwkAFZatn613LGhkhlcbdKO9pZHDJwKc6WpFdkCGHWmTgQogs2RDa-lhk3EDCEeBmaFToZ2vXGU9M3pVXGyfaAb3CDE_SYNsHFB7HrCL0Q8sAI7znKq-GXp7h-ncohisJlwAQzXC9wyHZjs8tr8TCCdX7yueJpsjUuTpsYdPp55Zer5w9YpBBQ-IHK2EIRd4Ff0zOUFiR6iKEsR9_6ucYVAJINoKXC8Ye2v1gQQUEi8Vc3bYETFoXmAxofP0qbxM21GLHB6sNazKA

contexts:
- context:
    cluster: lke30781
    namespace: default
    user: lke30781-admin
  name: lke30781-ctx

current-context: lke30781-ctx
